spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
              - key: extneral-application
                path: external-application.properties
      containers:
        - name: ${project.artifactId}
          resources:
            requests:
              cpu: "0.2"
              memory: 128Mi
            limits:
              cpu: "1.0"
              memory: 1024Mi
          volumeMounts:
            - mountPath: /config
              name: config
          env:
            - name: "CONFIG_LOCATION_EXTERNAL"
              value: "file:/config/external-application.properties"
              # Necessary, otherwise java console won't work in Openshift
            - name: "AB_JOLOKIA_HTTPS"
              value: "true"